name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    branch: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: QEMU install
      uses: docker/setup-qemu-action@v3

    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: build ls
      run: docker buildx ls

    - name: Log in to dockerhub
      run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Build Dockerfile image for amd64
      run: docker build --platform=linux/amd64 -t ademch/optimaaztec:amd64 --push .

    - name: Build Dockerfile image for arm64
      run: docker build --platform=linux/arm64 -t ademch/optimaaztec:arm64 --push .

    - name: Create manifest
      run: docker manifest create ademch/optimaaztec --amend ademch/optimaaztec:amd64 --amend ademch/optimaaztec:arm64

    - name: Push manifest to docker hub
      run: docker manifest push ademch/optimaaztec
